# Generated by Django 4.1.7 on 2023-04-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='profile',
            field=models.OneToOneField(default='my_friends', on_delete=django.db.models.deletion.CASCADE, to='mychatapp.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='mychatapp.friend'),
        ),
    ]
