# Generated by Django 4.1.7 on 2023-04-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0002_friend_profile_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='profile',
            field=models.OneToOneField(default='DEFAULT_VALUE', on_delete=django.db.models.deletion.CASCADE, to='mychatapp.profile'),
        ),
    ]
