# Generated by Django 4.1.7 on 2023-06-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_reciver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='img_reciver', to='mychatapp.profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='img_sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='img_sender', to='mychatapp.profile'),
        ),
    ]
