# Generated by Django 4.2 on 2023-06-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mychatapp", "0004_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="nudity",
        ),
    ]
