# Generated by Django 4.1.7 on 2023-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatapp', '0005_image_img_reciver_image_img_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nudity',
            field=models.BooleanField(default=False),
        ),
    ]
