# Generated by Django 4.2 on 2023-06-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mychatapp", "0006_image_nudity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="nudity",
        ),
    ]
