# Generated by Django 4.2 on 2023-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mychatapp", "0007_remove_image_nudity"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="nudity",
            field=models.BooleanField(default=False),
        ),
    ]
